### PR TITLE
feat:proposal make page

### PR DESCRIPTION
**Pull request by florashore**

### CODE REVIEW

**Review by coderprovider — COMMENTED** [review]
porposal page is great

**Comment by miraclaers** [comment]
thx

**Comment by coderprovider** [comment]
and sm design good

**Comment by miraclaers** [comment]
💓

**Review by Jermaine522 — COMMENTED** [review]
looks good

**Comment by miraclaers** [comment]
👍

**Comment by florashore** [comment]
thx

**Comment by florashore** [comment]
merged

**Comment by miraclaers** [comment]
thx

**Pull request merged**
