### PR TITLE
feat:locker page create

### PR DESCRIPTION
**Pull request by florashore**

### CODE REVIEW

**Comment by miraclaers** [comment]
button position must be fixed
and others good
!

**Comment by florashore** [comment]
have to fix the design
and will fix it

**Comment by coderprovider** [comment]
miraclaers is right
and how about res?

**Comment by florashore** [comment]
good

**Review by coderprovider — COMMENTED** [review]
is good

**Comment by florashore** [comment]
🙏

**Comment by coderprovider** [comment]
👍

**Review by miraclaers — COMMENTED** [review]
position must be modified

**Comment by miraclaers** [comment]
and 😀

**Review by Jermaine522 — COMMENTED** [review]
project structur is good

**Comment by florashore** [comment]
😀

**Comment by florashore** [comment]
?

**Comment by Jermaine522** [comment]
hover event?

**Comment by florashore** [comment]
yeah
implemented

**Comment by Jermaine522** [comment]
excellent

**Comment by florashore** [comment]
will merged

**Pull request merged**
